<a href="https://colab.research.google.com/github/M-Sai-Pranav/numpy-learning-phase-1/blob/main/phase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Numpy with chai aur code

In [4]:
import numpy as np

In [5]:
# creating array from list

In [6]:
arr_1d = np.array([1,2,3,4,5,6,7,8,9])

In [7]:
print("1D array : ", arr_1d)

1D array :  [1 2 3 4 5 6 7 8 9]


In [9]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [10]:
print("2D array : ", arr_2d)

2D array :  [[1 2 3]
 [4 5 6]]


In [11]:
# List vs Numpy array

In [12]:
py_list = [1,2,3]

In [13]:
print("Python list multiplication ", py_list*2)

Python list multiplication  [1, 2, 3, 1, 2, 3]


In [14]:
np_array = np.array([1,2,3])

In [15]:
print("Python array multiplication ", np_array*2) #element wise multiplication

Python array multiplication  [2 4 6]


In [18]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time()-start)


 List operation time:  0.08658814430236816


In [19]:
start = time.time()
np_array = np.arange(1000000)*2
print("\n Numpy operation time: ", time.time()-start)


 Numpy operation time:  0.010078907012939453


In [20]:
# creating array from scratch

In [21]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [22]:
ones = np.ones((2,3))
print("ones array: \n", ones)

ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
full = np.full((2,2), 7)
print("full array: \n", full)

full array: 
 [[7 7]
 [7 7]]


In [24]:
random = np.random.random((2,3))
print("random array: \n", random)

random array: 
 [[0.77933943 0.89212878 0.20534194]
 [0.98886524 0.8154744  0.26772151]]


In [26]:
sequence = np.arange(0,10,2)
print("sequence array: \n", sequence)

sequence array: 
 [0 2 4 6 8]


In [27]:
# vector, matrix and tensor

In [28]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [29]:
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [30]:
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: ", tensor)

Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [31]:
# Array properties

In [36]:
arr = np.array([[1,2,3],
                [4,5,"6.8"]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size ", arr.size)
print("DType ", arr.dtype)

Shape  (2, 3)
Dimension  2
Size  6
DType  <U21


In [37]:
# Array Reshaping

In [41]:
arr = np.arange(12)
print("Original array ", arr)
reshaped = arr.reshape((3,4))
print("Reshaped array ", reshaped)
flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

#ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n Raveled array ", raveled)

#Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
